project_id = "devnkdyfzlgspdlfuyam"

[functions.analyze-document-process]
verify_jwt = true

[functions.analyze-business-documents]
verify_jwt = true

[functions.create-client-from-invite]
verify_jwt = false

[functions.gov-br-signature]
verify_jwt = false

[functions.invite-collaborator]
verify_jwt = false

[functions.send-document-notification]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.send-unified-email]
verify_jwt = false

[functions.approve-admin-invite]
verify_jwt = false

[functions.verify-invite]
verify_jwt = false

[functions.get-invite-details]
verify_jwt = false

[functions.complete-invite-submission]
verify_jwt = false

[functions.get-process-requests]
verify_jwt = true

[functions.ensure-requests-for-process]
verify_jwt = false

[functions.complete-admin-signup]
verify_jwt = false

[functions.complete-internal-signature]
verify_jwt = true

