project_id = "devnkdyfzlgspdlfuyam"

[functions.invite-collaborator]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.verify-invite]
verify_jwt = false