// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://devnkdyfzlgspdlfuyam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldm5rZHlmemxnc3BkbGZ1eWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDE5MDEsImV4cCI6MjA3MTI3NzkwMX0.MMh37AaJ2S0-9s0FKgf8StBx74vQvzkX42Dji4dEi2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});